export const APP_START_INIT = 'APP_START_INIT';
export const APP_FINISH_INIT = 'APP_FINISH_INIT';

export const USER_GET_REQUEST = 'USER_GET_REQUEST';
export const USER_GET_SUCCESS = 'USER_GET_SUCCESS';
export const USER_GET_ERROR = 'USER_GET_ERROR';

export const USERS_GET_SUCCESS = 'USERS_GET_SUCCESS';
export const GROUPS_GET_SUCCESS = 'GROUPS_GET_SUCCESS';
export const GROUP_NEW_SUCCESS = 'GROUP_NEW_SUCCESS';
export const MESSAGES_GET_SUCCESS = 'MESSAGES_GET_SUCCESS';
export const MESSAGE_RECEIVE = 'MESSAGE_RECEIVE';
export const ONLINE_USERS = 'ONLINE_USERS';

export const INIT_SOCKET = 'INIT_SOCKET';
export const SOCKET_CONNECT = 'SOCKET_CONNECT';
export const SOCKET_OPEN = 'SOCKET_OPEN';
export const SOCKET_CLOSE = 'SOCKET_CLOSE';
export const SOCKET_ERROR = 'SOCKET_ERROR';
export const SOCKET_MESSAGE_RECEIVE = 'SOCKET_MESSAGE_RECEIVE';
export const SOCKET_MESSAGE_SEND = 'SOCKET_MESSAGE_SEND';

export const SOCKET_COMMANDS = {
  CHAT_GROUP_CREATE: 'CHAT_GROUP_CREATE',
  CHAT_PRIVATE_CREATE: 'CHAT_PRIVATE_CREATE',
  CHAT_UPDATE: 'CHAT_UPDATE',
  CHAT_DELETE: 'CHAT_DELETE',
  CHAT_LEAVE: 'CHAT_LEAVE',
  CHAT_JOIN: 'CHAT_JOIN',
  CHATS_GET_BY_USER_ID: 'CHATS_GET_BY_USER_ID',
  MESSAGE_SEND: 'MESSAGE_SEND',
  MESSAGE_UPDATE: 'MESSAGE_UPDATE',
  MESSAGE_DELETE: 'MESSAGE_DELETE',
  MESSAGES_GET_BY_CHAT_ID: 'MESSAGES_GET_BY_CHAT_ID',
  VIDEO_CALL_START: 'VIDEO_CALL_START',
  VIDEO_CALL_JOIN: 'VIDEO_CALL_JOIN',
  VIDEO_CALL_EXIT: 'VIDEO_CALL_EXIT',
};
