export const USER_AUTH_REQUEST = 'USER_AUTH_REQUEST';
export const USER_AUTH_ERROR = 'USER_AUTH_ERROR';
export const USER_IS_AUTH_SET = 'USER_IS_AUTH_SET';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR';

export const CONFIRM_MAIL_REQUEST = 'CONFIRM_MAIL_REQUEST';
export const CONFIRM_MAIL_SUCCESS = 'CONFIRM_MAIL_SUCCESS';
export const CONFIRM_MAIL_ERROR = 'CONFIRM_MAIL_ERROR';

export const APP_LOG_OUT = 'APP_LOG_OUT';
